name: "Ruby on Rails CI"
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Set Progressive tests step
        run: STEP="${{ github.event.pull_request.title }}" | grep -o "^#[0-9]*" | sed 's/#//'; STEP=${STEP:-0};echo "STEP=$STEP" >> $GITHUB_ENV
      - name: Display ref
        run: echo ${{ github.event.pull_request.title }}
      - name: Display step
        run: echo ${{ env.STEP }}
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.2.4
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rake
